# Generated by Django 6.0.1 on 2026-07-19 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0035_alter_donorworkflow_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodUnitCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(default='Platelet Unit', max_length=100)),
                ('sample_type', models.CharField(default='Platelet Concentrate', max_length=100)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive')], default='PENDING', max_length=20)),
                ('incubation_days', models.IntegerField(default=7, help_text='Incubation period in days')),
                ('current_incubation_day', models.IntegerField(default=1)),
                ('growth_status', models.CharField(default='No Growth Yet', max_length=100)),
                ('final_interpretation', models.CharField(choices=[('STERILE', 'Sterile Blood Component'), ('CONTAMINATED', 'Bacterial Contamination'), ('PENDING', 'Pending')], default='PENDING', max_length=100)),
                ('unit_status', models.CharField(choices=[('RELEASED', 'Released for Transfusion'), ('QUARANTINED', 'Quarantined'), ('DISCARDED', 'Discarded')], default='QUARANTINED', max_length=50)),
                ('organism_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gram_stain_result', models.CharField(blank=True, max_length=200, null=True)),
                ('colony_count', models.CharField(blank=True, max_length=100, null=True)),
                ('antibiotic_susceptibility', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approved_by_name', models.CharField(default='Dr. Ahmed (Microbiologist)', max_length=150)),
                ('approval_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cultures', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_results', to='clinical.donorworkflow')),
            ],
        ),
    ]
